export { default as question } from './question'
export { default as auth } from './auth'
export { default as post } from './posts'
export { default as visa } from './visa'
export { default as requirment } from './requirment'